{
 "title": "Cryptobot Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Spot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETHBTC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT price AS buy_price,time_hr FROM public.trades WHERE symbol = 'ETHBTC' AND \"isBuyer\" = True\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_price,time_hr FROM public.trades WHERE symbol = 'ETHBTC' AND \"isBuyer\" = False\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS buy_order,time_hr FROM public.orders WHERE symbol = 'ETHBTC' AND side = 'BUY'"
    },
    {
     "rawSql": "SELECT price AS sell_order,time_hr FROM public.orders WHERE symbol = 'ETHBTC' AND side = 'SELL'"
    },
    {
     "rawSql": "SELECT price,time_hr FROM exchange_prices WHERE symbol = 'ETHBTC'"
    }
   ]
  },
  {
   "title": "XRPETH",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT price AS sell_price,time_hr FROM public.trades WHERE symbol = 'XRPETH' AND \"isBuyer\" = False\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS buy_price,time_hr FROM public.trades WHERE symbol = 'XRPETH' AND \"isBuyer\" = True\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_order,time_hr FROM public.orders WHERE symbol = 'XRPETH' AND side = 'SELL'"
    },
    {
     "rawSql": "SELECT price AS buy_order,time_hr FROM public.orders WHERE symbol = 'XRPETH' AND side = 'BUY'"
    },
    {
     "rawSql": "SELECT price,time_hr FROM exchange_prices WHERE symbol = 'XRPETH'"
    }
   ]
  },
  {
   "title": "XRPBTC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT price AS buy_price,time_hr FROM public.trades WHERE symbol = 'XRPBTC' AND \"isBuyer\" = True\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_price,time_hr FROM public.trades WHERE symbol = 'XRPBTC' AND \"isBuyer\" = False\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_order,time_hr FROM public.orders WHERE symbol = 'XRPBTC' AND side = 'SELL'"
    },
    {
     "rawSql": "SELECT price AS buy_order,time_hr FROM public.orders WHERE symbol = 'XRPBTC' AND side = 'BUY'"
    },
    {
     "rawSql": "SELECT price,time_hr FROM exchange_prices WHERE symbol = 'XRPBTC'"
    }
   ]
  },
  { "title": "Futures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "BTCUSDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT price AS sell_price,time_hr FROM public.trades WHERE symbol = 'BTCUSDT' AND \"isBuyer\" = False\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_order,time_hr FROM public.orders WHERE symbol = 'BTCUSDT' AND side = 'SELL'"
    },
    {
     "rawSql": "SELECT a.time_hr,a.price, \r\n       AVG(a.price)\r\n       OVER(ORDER BY a.time_hr ROWS BETWEEN 12 PRECEDING AND CURRENT ROW)\r\n       AS ma_1hr,\r\n\t   AVG(a.price)\r\n       OVER(ORDER BY a.time_hr ROWS BETWEEN 72 PRECEDING AND CURRENT ROW)\r\n       AS ma_6hr\r\n\tFROM public.exchange_prices a \r\n\tWHERE symbol = 'BTCUSDT';"
    }
   ]
  },
  {
   "title": "ETHUSDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT price AS sell_price,time_hr FROM public.trades WHERE symbol = 'ETHUSDT' AND \"isBuyer\" = False\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_order,time_hr FROM public.orders WHERE symbol = 'ETHUSDT' AND side = 'SELL'"
    },
    {
     "rawSql": "SELECT a.time_hr,a.price, \r\n       AVG(a.price)\r\n       OVER(ORDER BY a.time_hr ROWS BETWEEN 12 PRECEDING AND CURRENT ROW)\r\n       AS ma_1hr,\r\n\t   AVG(a.price)\r\n       OVER(ORDER BY a.time_hr ROWS BETWEEN 72 PRECEDING AND CURRENT ROW)\r\n       AS ma_6hr\r\n\tFROM public.exchange_prices a \r\n\tWHERE symbol = 'ETHUSDT';"
    }
   ]
  },
  {
   "title": "XRPUSDT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT price AS sell_price,time_hr FROM public.trades WHERE symbol = 'XRPUSDT' AND \"isBuyer\" = False\r\nORDER BY time_hr DESC"
    },
    {
     "rawSql": "SELECT price AS sell_order,time_hr FROM public.orders WHERE symbol = 'XRPUSDT' AND side = 'SELL'"
    },
    {
     "rawSql": "SELECT a.time_hr,a.price, \r\n       AVG(a.price)\r\n       OVER(ORDER BY a.time_hr ROWS BETWEEN 12 PRECEDING AND CURRENT ROW)\r\n       AS ma_1hr,\r\n\t   AVG(a.price)\r\n       OVER(ORDER BY a.time_hr ROWS BETWEEN 72 PRECEDING AND CURRENT ROW)\r\n       AS ma_6hr\r\n\tFROM public.exchange_prices a \r\n\tWHERE symbol = 'XRPUSDT';"
    }
   ]
  },
  { "title": "Assets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Asset Holding (USD)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT * FROM assets_usd ORDER BY time_hr ASC"
    }
   ]
  },
  {
   "title": "Trades",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Trades",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "rawSql": "SELECT symbol,price,qty,\"quoteQty\",\"isBuyer\",time_hr FROM public.trades\r\nORDER BY time_hr DESC"
      }
     ]
    },
    {
     "title": "Open Orders",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "rawSql": "SELECT symbol,price,\"origQty\",\"executedQty\",side,time_hr FROM  orders ORDER BY time_hr DESC"
      }
     ]
    }
   ]
  }
 ]
}